services:
  db:
    image: postgis/postgis:13-3.2-alpine
    restart: always
    environment:
      POSTGRES_DB: cartondes
      POSTGRES_USER: cartondes_dba
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    # ports:
    #   - "5555:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  geoserver:
    image: docker.osgeo.org/geoserver:2.26.1
    restart: always
    environment:
      - SKIP_DEMO_DATA=true
      - CORS_ENABLED=true
      - CORS_ALLOWED_ORIGINS=*
      - CORS_ALLOWED_METHODS=GET
      - GEOSERVER_ADMIN_USER=cartondes
      - GEOSERVER_ADMIN_PASSWORD=$GEOSERVER_PASSWORD
    # ports:
    #   - "8080:8080"
    volumes:
      - geo-data:/opt/geoserver_data

  app:
    image: ghcr.io/mastergeonum/cartondes:main
    build: .
    restart: always
    # ports:
    #   - "1234:1234"
    environment:
      POSTGRES_HOST: db
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      CARTONDES_USER: $CARTONDES_USER
      CARTONDES_PASSWORD: $CARTONDES_PASSWORD
  
  proxy:
    image: nginx:latest
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

volumes:
  db-data:
  geo-data: